---
title: "Tidy Tuesday Astronauts"
output: github_document
---

```{r}
library(tidyverse) #data mgmt
library(extrafont) #add different font
library(ggpubr) #plot pic to plot background
library(jpeg) #read in background image

nauts<-  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
```

```{r}
nauts
```
### number of astronauts in df
```{r}
length(unique(nauts$name))
```
is it the same as "number variable"... yes
```{r}
length(unique(nauts$number))
```

### Nationality

How many different nationalities
```{r}
nauts %>%
  distinct(number, .keep_all=TRUE) %>% #keep each unique naut
  group_by(nationality) %>% 
  tally() %>%
  arrange(desc(n))
```

Looks like some could be added into US or Russia
```{r}
nauts %>%
  filter(grepl("U.S.", nationality)) %>%
  group_by(nationality) %>%
  tally()
```

Create 3 nationality groups (US, Russia, Other)
```{r}
nauts<- nauts %>%
  mutate(nation_bi=case_when(
    grepl("U.S.$", nationality)~"US",
    grepl("U.S.S.R", nationality)~ "USSR/Russia",
    TRUE~"Other"))

nauts %>%
  group_by(nation_bi) %>%
  tally()
```
Average age at first mission by nation
```{r}
age_first_df <-nauts %>%
  distinct(number, .keep_all=TRUE) %>% #keep each unique naut
  group_by(nation_bi) %>% 
  summarise(age=mean((year_of_mission-year_of_birth), na.rm=TRUE)) %>%
  mutate(time="First mission")

age_first_df 
```

Average age at last mission
```{r}
age_last_df<- nauts %>%
  arrange(desc(id, number)) %>%
  distinct(number, .keep_all=TRUE) %>% #keep each unique naut
  group_by(nation_bi) %>% 
  summarise(age=mean((year_of_mission-year_of_birth), na.rm=TRUE)) %>%
  mutate(time="Last mission")

age_last_df
```
Merge dfs for visual
```{r}
naut_age_df<- rbind(age_first_df, age_last_df)

naut_age_df
```
Theme
```{r}
library(ggdark)

my_theme<- dark_theme_gray(base_family = "Comic Sans MS", base_size = 14) + 
  theme(plot.title = element_text(family = "Comic Sans MS"),
        plot.background = element_rect(fill = "grey10"),
        panel.background = element_blank(),
        panel.grid.major = element_line(color = "grey30", size = 0.2),
        panel.grid.minor = element_line(color = "grey30", size = 0.2),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        legend.key = element_blank())


#pic
myimg<- readJPEG("C:\\Users\\rebekahjacob\\Box\\T drive data\\Tidy Tuesdays\\space_pic.jpg")
```


```{r}
fig1 <- ggplot(data = naut_age_df, aes(x = nation_bi, y=age, fill = time)) +
  background_image(myimg) + #add image to background BEFORE geom_bar
            geom_bar(stat = "identity",  width = 0.7, position = "dodge", alpha=0.5) +
          geom_text(aes(label = round(age, 1)), size = 4 , hjust = 0.6 , vjust = -0.25, 
                    position = position_dodge(width = 0.7))+
          my_theme +
        scale_fill_manual(values = c("mediumpurple", "paleturquoise3"))+
        labs(title = "Average age at first and last mission by nationality",
             x = "", y = "Mean age in years",
             caption = "@RRJacob_STL")+
   ylim(c(0, 50)) 
  
fig1   
```


